add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_data_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/chopper.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pipeline_register_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pool_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_data_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pipeline_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/unrolled_loop_counter.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_atrb_generator.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_register_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_register_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_arbiter.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_bank_memory_reader.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_bank_memory_writer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_intake_line_selector.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_outlet_line_selector.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_register_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_arbiter_integer_arch.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_arbiter_one_hot_arch.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_altera_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_model.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_xilinx_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_xilinx_ultrascale_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/convolution/convolution_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_intake.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_outlet.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_channel_reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_generator_with_padding.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/register_access_decoder.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/util.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_types.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/reader.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/sync.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/vocal.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_channel_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_stream_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_master_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_models.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_stream_master_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/marchal.vhd
add_vhdl_file sources_1 QCONV ../../../src/main/vhdl/qconv_params.vhd
add_vhdl_file sources_1 QCONV ../../../src/main/vhdl/qconv_strip_in_data_buffer.vhd
add_vhdl_file sources_1 QCONV ../../../src/main/vhdl/qconv_strip_registers.vhd
add_vhdl_file sim_1     WORK ../../../PipeWorkTest/src/test/vhdl/image_stream_models/image_stream_player.vhd
add_vhdl_file sim_1     WORK ../../../PipeWorkTest/src/test/vhdl/image_stream_models/image_stream_slave_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/qconv_strip_in_data_buffer_test_bench.vhd
